sudo: false
language: php
php:
    - 5.5
    - 5.6
    - hhvm
before_script:
    - composer self-update
    - composer install --prefer-source
script:
    - chmod -R 777 tests/build
    - ./vendor/bin/phpunit
    - ./vendor/bin/phpspec run -v
    - ./vendor/bin/behat
    - ./vendor/bin/codecept build --config=codeception_tests
    - ./vendor/bin/codecept run --config=codeception_tests
