<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
$I->m('engineer');
$I->amCalled('1');
$I->answer('1');
$I->am('Gentleman');
$I->amCalled('hello');
$I->answer('hello');
$I->amCalled('4');
$I->answer('4');
$I->lookForwardTo('want crazy');
$I->amCalled('3');
$I->answer('aho');
$I->amCalled('6');
$I->answer('aho');
$I->amCalled('13');
$I->answer('aho');
$I->amCalled('1258736984873');
$I->answer('aho');
